CREATE DATABASE IF NOT EXISTS portfolio DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE portfolio;

CREATE TABLE IF NOT EXISTS project(
    idx INT PRIMARY KEY,
    name VARCHAR(64) UNIQUE,
    role VARCHAR(256) NOT NULL,
    stack VARCHAR(256) NULL DEFAULT NULL,
    brief VARCHAR(512) NULL DEFAULT NULL,
    description VARCHAR(2048) NOT NULL,
    links VARCHAR(32) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS link(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(1024) UNIQUE,
    type VARCHAR(32) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS interest(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    icon VARCHAR(32) NULL DEFAULT NULL
);